import type { Level } from "../levels";

/** Practice phrases for the pronunciation trainer, chosen to target sounds that are hard for Russian/Uzbek speakers. */
export const PHRASES: Record<Level, string[]> = {
  A1: [
    "Thank you very much.",
    "I think this is the right way.",
    "We have three white rabbits.",
    "What is the weather like today?",
    "This is my brother and his wife.",
  ],
  A2: [
    "I would like a cup of green tea, please.",
    "The thirtieth of January is on Thursday.",
    "We went to the village very early.",
    "Her hair is really long and red.",
    "I've never heard this word before.",
  ],
  B1: [
    "Although the weather was awful, we enjoyed the walk.",
    "I thoroughly enjoyed the theatre performance.",
    "World leaders gathered in Washington.",
    "Vegetables are very healthy for everyone.",
  ],
  B2: [
    "Through thick and thin, they worked together.",
    "The development of renewable energy is essential.",
    "She whispered something worth remembering.",
    "The clothes were thoroughly washed and ironed.",
  ],
  C1: [
    "Statistically, the phenomenon is rather anomalous.",
    "The thesis was thoroughly scrutinised by the committee.",
    "Particularly worthwhile literature rarely gets attention.",
  ],
  C2: [
    "The sixth sick sheikh's sixth sheep's sick.",
    "Rural juror regulations were unusually thorough.",
    "Worcestershire sauce is surprisingly versatile.",
  ],
};

/** Small offline IPA dictionary for common tricky words. */
export const IPA: Record<string, string> = {
  thank: "θæŋk",
  think: "θɪŋk",
  this: "ðɪs",
  the: "ðə",
  three: "θriː",
  white: "waɪt",
  rabbits: "ˈræbɪts",
  weather: "ˈweðər",
  what: "wɒt",
  brother: "ˈbrʌðər",
  wife: "waɪf",
  would: "wʊd",
  thirtieth: "ˈθɜːtiəθ",
  thursday: "ˈθɜːzdeɪ",
  january: "ˈdʒænjuəri",
  village: "ˈvɪlɪdʒ",
  very: "ˈveri",
  hair: "heər",
  really: "ˈrɪəli",
  heard: "hɜːd",
  word: "wɜːd",
  although: "ɔːlˈðəʊ",
  awful: "ˈɔːfl",
  thoroughly: "ˈθʌrəli",
  theatre: "ˈθɪətər",
  world: "wɜːld",
  washington: "ˈwɒʃɪŋtən",
  vegetables: "ˈvedʒtəblz",
  through: "θruː",
  thick: "θɪk",
  thin: "θɪn",
  development: "dɪˈveləpmənt",
  whispered: "ˈwɪspərd",
  worth: "wɜːθ",
  clothes: "kləʊðz",
  statistically: "stəˈtɪstɪkli",
  phenomenon: "fəˈnɒmɪnən",
  anomalous: "əˈnɒmələs",
  thesis: "ˈθiːsɪs",
  particularly: "pəˈtɪkjələli",
  worthwhile: "ˌwɜːθˈwaɪl",
  literature: "ˈlɪtrətʃər",
  sixth: "sɪksθ",
  rural: "ˈrʊərəl",
  worcestershire: "ˈwʊstərʃər",
  tea: "tiː",
  together: "təˈɡeðər",
  everyone: "ˈevriwʌn",
};
