import type { Level } from "../levels";

export type TopicSeed = {
  slug: string;
  level: Level;
  icon: string;
  proOnly?: boolean;
  title: { ru: string; en: string; uz: string };
  desc: { ru: string; en: string; uz: string };
  starter: string;
  /** Follow-up questions the offline tutor uses to keep the conversation going. */
  questions: string[];
};

export const TOPICS: TopicSeed[] = [
  // ───── A1 ─────
  {
    slug: "greetings",
    level: "A1",
    icon: "Hand",
    title: { ru: "Знакомство", en: "Greetings & introductions", uz: "Tanishuv" },
    desc: { ru: "Привет, как тебя зовут, откуда ты", en: "Hello, your name, where you are from", uz: "Salom, ismingiz, qayerdansiz" },
    starter: "Hi! I'm Ustoz, your English tutor. What's your name?",
    questions: ["Nice to meet you! Where are you from?", "How old are you?", "What do you do? Are you a student?", "What languages do you speak?"],
  },
  {
    slug: "family",
    level: "A1",
    icon: "Users",
    title: { ru: "Семья", en: "Family", uz: "Oila" },
    desc: { ru: "Родители, братья и сёстры", en: "Parents, brothers and sisters", uz: "Ota-ona, aka-uka va opa-singillar" },
    starter: "Let's talk about family. Do you have a big family?",
    questions: ["How many brothers and sisters do you have?", "What is your mother's name?", "Who do you live with?", "What does your father do?"],
  },
  {
    slug: "food",
    level: "A1",
    icon: "Soup",
    title: { ru: "Еда и плов", en: "Food & plov", uz: "Taom va palov" },
    desc: { ru: "Любимая еда, узбекская кухня", en: "Favourite food, Uzbek cuisine", uz: "Sevimli taom, oʻzbek oshxonasi" },
    starter: "Let's talk about food! What is your favourite food?",
    questions: ["Do you like plov? Who cooks it in your family?", "What do you usually eat for breakfast?", "Do you like tea or coffee?", "Can you cook? What can you make?"],
  },
  {
    slug: "numbers-time",
    level: "A1",
    icon: "Clock",
    title: { ru: "Числа и время", en: "Numbers & time", uz: "Sonlar va vaqt" },
    desc: { ru: "Который час, даты, цены", en: "Telling the time, dates, prices", uz: "Soat necha, sanalar, narxlar" },
    starter: "Let's practise numbers and time. What time do you get up?",
    questions: ["What time is it now?", "When is your birthday?", "What is your phone number? You can invent one!", "How many hours do you sleep?"],
  },
  {
    slug: "daily-routine",
    level: "A1",
    icon: "Sun",
    title: { ru: "Мой день", en: "Daily routine", uz: "Kun tartibi" },
    desc: { ru: "Утро, работа, вечер", en: "Morning, work, evening", uz: "Ertalab, ish, kechqurun" },
    starter: "Tell me about your day. What do you do in the morning?",
    questions: ["How do you get to work or school?", "What do you do in the evening?", "What time do you go to bed?", "What do you do at the weekend?"],
  },
  {
    slug: "my-city",
    level: "A1",
    icon: "Building2",
    title: { ru: "Мой город — Ташкент", en: "My city — Tashkent", uz: "Mening shahrim — Toshkent" },
    desc: { ru: "Места, метро, парки", en: "Places, metro, parks", uz: "Joylar, metro, bogʻlar" },
    starter: "Let's talk about Tashkent. Which part of the city do you live in?",
    questions: ["What is your favourite place in Tashkent?", "Do you take the metro? Which station is near your home?", "Is there a park near your house?", "What can tourists see in your city?"],
  },
  // ───── A2 ─────
  {
    slug: "shopping",
    level: "A2",
    icon: "ShoppingBag",
    title: { ru: "Покупки и базар", en: "Shopping & bazaar", uz: "Xarid va bozor" },
    desc: { ru: "Chorsu, цены, торг", en: "Chorsu bazaar, prices, bargaining", uz: "Chorsu, narxlar, savdolashish" },
    starter: "Let's go shopping! Do you prefer bazaars or supermarkets?",
    questions: ["What did you buy last time at the bazaar?", "Do you like to bargain? How do you do it?", "How much does a kilo of apples cost?", "Do you shop online?"],
  },
  {
    slug: "weather",
    level: "A2",
    icon: "CloudSun",
    title: { ru: "Погода и сезоны", en: "Weather & seasons", uz: "Ob-havo va fasllar" },
    desc: { ru: "Жаркое лето, снег, весна", en: "Hot summers, snow, spring", uz: "Issiq yoz, qor, bahor" },
    starter: "What's the weather like today in Tashkent?",
    questions: ["What is your favourite season and why?", "What do you do when it is very hot?", "Did it snow last winter?", "What do you usually do in spring for Navruz?"],
  },
  {
    slug: "hobbies",
    level: "A2",
    icon: "Palette",
    title: { ru: "Хобби", en: "Hobbies", uz: "Qiziqishlar" },
    desc: { ru: "Спорт, музыка, игры", en: "Sport, music, games", uz: "Sport, musiqa, oʻyinlar" },
    starter: "What do you like doing in your free time?",
    questions: ["How often do you do it?", "When did you start?", "Do you play any sport?", "What music do you listen to?"],
  },
  {
    slug: "travel",
    level: "A2",
    icon: "Plane",
    title: { ru: "Путешествия", en: "Travel & transport", uz: "Sayohat va transport" },
    desc: { ru: "Самарканд, Бухара, поезд", en: "Samarkand, Bukhara, trains", uz: "Samarqand, Buxoro, poyezd" },
    starter: "Have you ever been to Samarkand or Bukhara?",
    questions: ["How did you get there?", "Where would you like to travel next?", "Do you prefer trains or planes?", "What do you always take on a trip?"],
  },
  {
    slug: "last-weekend",
    level: "A2",
    icon: "CalendarDays",
    title: { ru: "Прошлые выходные", en: "Last weekend", uz: "Oʻtgan dam olish kunlari" },
    desc: { ru: "Past Simple в живом разговоре", en: "Past Simple in real conversation", uz: "Past Simple jonli suhbatda" },
    starter: "What did you do last weekend?",
    questions: ["Who were you with?", "What did you eat?", "Did you go anywhere interesting?", "Was it a good weekend? Why?"],
  },
  {
    slug: "health",
    level: "A2",
    icon: "HeartPulse",
    proOnly: true,
    title: { ru: "Здоровье и врач", en: "Health & the doctor", uz: "Salomatlik va shifokor" },
    desc: { ru: "Симптомы, аптека, советы", en: "Symptoms, pharmacy, advice", uz: "Belgilar, dorixona, maslahatlar" },
    starter: "Imagine you are at the doctor's. What's the matter?",
    questions: ["How long have you felt like this?", "Do you take any medicine?", "What do you do to stay healthy?", "How often do you exercise?"],
  },
  // ───── B1 ─────
  {
    slug: "work",
    level: "B1",
    icon: "Briefcase",
    title: { ru: "Работа и карьера", en: "Work & careers", uz: "Ish va karyera" },
    desc: { ru: "Обязанности, коллеги, мечты", en: "Duties, colleagues, ambitions", uz: "Vazifalar, hamkasblar, orzular" },
    starter: "Let's talk about work. What do you do, or what would you like to do?",
    questions: ["What do you like most about your job or studies?", "What skills are important in your field?", "Where do you see yourself in five years?", "Would you like to work abroad? Why?"],
  },
  {
    slug: "education",
    level: "B1",
    icon: "GraduationCap",
    title: { ru: "Образование", en: "Education", uz: "Taʼlim" },
    desc: { ru: "Школа, университет, онлайн-курсы", en: "School, university, online courses", uz: "Maktab, universitet, onlayn kurslar" },
    starter: "What was your favourite subject at school?",
    questions: ["Is online learning as good as classroom learning?", "What would you change about schools in Uzbekistan?", "Why are you learning English?", "What's the best way to learn a language?"],
  },
  {
    slug: "technology",
    level: "B1",
    icon: "Smartphone",
    title: { ru: "Технологии", en: "Technology", uz: "Texnologiyalar" },
    desc: { ru: "Смартфоны, приложения, AI", en: "Phones, apps, AI", uz: "Smartfonlar, ilovalar, AI" },
    starter: "How many hours a day do you spend on your phone?",
    questions: ["Which apps can't you live without?", "Do you think AI will change your job?", "What technology would you like to have in the future?", "Are social networks good or bad for young people?"],
  },
  {
    slug: "movies-books",
    level: "B1",
    icon: "Clapperboard",
    title: { ru: "Кино и книги", en: "Films & books", uz: "Kino va kitoblar" },
    desc: { ru: "Рассказываем сюжет, мнения", en: "Telling plots, sharing opinions", uz: "Syujetni aytib berish, fikrlar" },
    starter: "What's the last film you watched? Did you enjoy it?",
    questions: ["What was it about?", "Would you recommend it? Why?", "Do you prefer books or their film versions?", "Who is your favourite actor or writer?"],
  },
  {
    slug: "future-plans",
    level: "B1",
    icon: "Rocket",
    title: { ru: "Планы на будущее", en: "Future plans", uz: "Kelajak rejalari" },
    desc: { ru: "will, going to, Present Continuous", en: "will, going to, Present Continuous", uz: "will, going to, Present Continuous" },
    starter: "What are you going to do next summer?",
    questions: ["What will you do if you have more free time?", "What is one goal you want to achieve this year?", "Are you planning to study further?", "Where will you be in ten years, do you think?"],
  },
  // ───── B2 ─────
  {
    slug: "environment",
    level: "B2",
    icon: "Leaf",
    title: { ru: "Экология", en: "Environment", uz: "Ekologiya" },
    desc: { ru: "Арал, вода, климат", en: "The Aral Sea, water, climate", uz: "Orol, suv, iqlim" },
    starter: "What do you think is the biggest environmental problem in Central Asia?",
    questions: ["What could be done about the Aral Sea?", "Do you try to live sustainably? How?", "Should governments ban plastic bags?", "How has the climate changed where you live?"],
  },
  {
    slug: "culture",
    level: "B2",
    icon: "Landmark",
    title: { ru: "Культура и традиции", en: "Culture & traditions", uz: "Madaniyat va anʼanalar" },
    desc: { ru: "Свадьбы, праздники, гостеприимство", en: "Weddings, holidays, hospitality", uz: "Toʻylar, bayramlar, mehmondoʻstlik" },
    starter: "How would you explain Uzbek hospitality to a foreigner?",
    questions: ["Which tradition would you like to keep forever?", "How are weddings different now compared to the past?", "What surprised you about other cultures?", "Is globalisation a threat to local traditions?"],
  },
  {
    slug: "job-interview",
    level: "B2",
    icon: "Handshake",
    title: { ru: "Собеседование", en: "Job interview", uz: "Ish suhbati" },
    desc: { ru: "Тренируем реальные вопросы", en: "Practise real interview questions", uz: "Haqiqiy savollarni mashq qilamiz" },
    starter: "Let's do a mock interview. Tell me a little about yourself.",
    questions: ["What is your greatest strength?", "Tell me about a difficult situation at work and how you handled it.", "Why do you want this position?", "Where do you see yourself in five years?"],
  },
  {
    slug: "media",
    level: "B2",
    icon: "Newspaper",
    title: { ru: "Новости и медиа", en: "News & media", uz: "Yangiliklar va media" },
    desc: { ru: "Фейки, источники, мнения", en: "Fake news, sources, opinions", uz: "Soxta xabarlar, manbalar, fikrlar" },
    starter: "Where do you usually get your news from?",
    questions: ["How can you tell if a story is fake?", "Should social networks be responsible for what users post?", "Has the internet made journalism better or worse?", "What news story interested you recently?"],
  },
  // ───── C1 ─────
  {
    slug: "business",
    level: "C1",
    icon: "TrendingUp",
    title: { ru: "Бизнес и переговоры", en: "Business & negotiation", uz: "Biznes va muzokaralar" },
    desc: { ru: "Стартапы, сделки, презентации", en: "Start-ups, deals, pitches", uz: "Startaplar, bitimlar, taqdimotlar" },
    starter: "Imagine you're pitching a start-up to investors in Tashkent. What's your idea?",
    questions: ["What would make investors sceptical?", "How would you respond if they offered half the valuation?", "What is the key to a successful negotiation?", "How is doing business in Uzbekistan changing?"],
  },
  {
    slug: "debate",
    level: "C1",
    icon: "Scale",
    title: { ru: "Дебаты", en: "Debate & opinion", uz: "Munozara" },
    desc: { ru: "Аргументы, контраргументы", en: "Arguments and counter-arguments", uz: "Dalillar va qarshi dalillar" },
    starter: "Let's debate: 'University education should be free for everyone.' Do you agree?",
    questions: ["What would the opposing side argue?", "How would you fund it?", "Can you think of a country where this works well?", "Has your opinion changed during our discussion?"],
  },
  {
    slug: "academic",
    level: "C1",
    icon: "PenLine",
    proOnly: true,
    title: { ru: "IELTS и академический стиль", en: "IELTS & academic style", uz: "IELTS va akademik uslub" },
    desc: { ru: "Writing Task 2, связки, лексика", en: "Writing Task 2, linking, vocabulary", uz: "Writing Task 2, bogʻlovchilar, lugʻat" },
    starter: "Let's practise IELTS Speaking Part 3. Why do you think people's reading habits have changed?",
    questions: ["Could you give a specific example?", "What might the long-term consequences be?", "How might this differ between generations?", "To what extent should governments intervene?"],
  },
  // ───── C2 ─────
  {
    slug: "idioms",
    level: "C2",
    icon: "Sparkles",
    title: { ru: "Идиомы и нюансы", en: "Idioms & nuance", uz: "Iboralar va nozikliklar" },
    desc: { ru: "Звучать как носитель", en: "Sound like a native speaker", uz: "Ona tilida soʻzlashuvchidek gapirish" },
    starter: "Have you ever had to 'bite the bullet'? Tell me about it.",
    questions: ["Can you think of an Uzbek or Russian proverb with a similar meaning?", "When did you last 'go the extra mile'?", "What's something that 'drives you up the wall'?", "Which English idiom do you find the strangest?"],
  },
  {
    slug: "philosophy",
    level: "C2",
    icon: "BookOpen",
    title: { ru: "Литература и философия", en: "Literature & philosophy", uz: "Adabiyot va falsafa" },
    desc: { ru: "Навои, Толстой, смысл жизни", en: "Navoi, Tolstoy, the meaning of life", uz: "Navoiy, Tolstoy, hayot mazmuni" },
    starter: "Alisher Navoi wrote in both Chagatai and Persian. Does the language we write in shape what we can say?",
    questions: ["Is a translation ever truly faithful?", "Which book changed the way you think?", "Can happiness be a goal in itself?", "What would you ask Navoi if you could meet him?"],
  },
];

export const topicBySlug = (slug?: string | null) => TOPICS.find((t) => t.slug === slug);
