// prisma/schema.prisma (SQLite, local) → prisma/postgres/schema.prisma (Neon on Vercel).
// Only the datasource differs: DATABASE_URL is the pooled connection, DATABASE_URL_UNPOOLED the direct one for migrations.
// `--check` fails if the generated file is out of date (CI).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const SRC = "prisma/schema.prisma";
const OUT = "prisma/postgres/schema.prisma";

const source = readFileSync(SRC, "utf8").replace(/\r\n/g, "\n");
const datasource = /datasource db \{[^}]*\}/;
if (!datasource.test(source)) throw new Error(`No datasource block in ${SRC}`);

const header = "// Generated by scripts/pg-schema.mjs from prisma/schema.prisma — edit that file, then run `npm run db:pg:schema`.\n\n";
const result =
  header +
  source.replace(datasource, ['datasource db {', '  provider  = "postgresql"', '  url       = env("DATABASE_URL")', '  directUrl = env("DATABASE_URL_UNPOOLED")', "}"].join("\n"));

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== result) {
    console.error(`${OUT} is out of date: run npm run db:pg:schema and add a migration (npm run db:pg:diff <name>).`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date.`);
} else {
  mkdirSync("prisma/postgres", { recursive: true });
  writeFileSync(OUT, result);
  console.log(`Wrote ${OUT}`);
}
